---
- name: Install Java 17 and Maven on Ubuntu
  hosts: all
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Ensure JAVA_HOME is set globally
      lineinfile:
        path: /etc/environment
        regexp: '^JAVA_HOME='
        line: 'JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'
        state: present

    - name: Reload environment variables
      shell: source /etc/environment
      args:
        executable: /bin/bash

    - name: Verify Java installation
      command: java -version
      register: java_version
      ignore_errors: yes

    - name: Show Java version
      debug:
        var: java_version.stderr_lines

    - name: Verify Maven installation
      command: mvn -version
      register: maven_version
      ignore_errors: yes

    - name: Show Maven version
      debug:
        var: maven_version.stdout_lines
